apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nginx
  namespace: {{ .Release.Namespace | quote }}
spec:
  template:
    type: Opaque
    metadata:      
  encryptedData:
    - foo : "AgA+wdfiujorafy03fES+/hAk76cP1+m/VuUsQ1eDZKT/sBcoRjHsqqmOhcK6PisYfJe6TI/dqAI6AtmSzcEEieLvw6qKByo9Mr/miW8h+oJviEs5PiKVrasBK9GCc6yW6rQ77hCv8yiDPZuvosuH7HweXe5/4mv7LrX6A/FyND6DzYwCkyo9kuRiqcpHbmbj7/7TUcv9XN+r5eqIS8zgT/HZW2m5PqDRd5uoY3bMumizwZ3LL30jb3DGaMJVnVZdSoVQ78ADLg8aiBZCXnNjurnM4NgxovQT3Pw4O6B09/Z0gOmxbl+ryzcoNn7OuNWNSFq36SGy4F9bf1dY1e4Ffp6Jx3GMSYdZsFZGrrZDQUg93TGlFyPaCR85yo8RN/l1TsVcaxUcikwoUi0JePlk3Pace0e6DafTXrpGFofoUL/ixxFw3x7ks0n1/J9jQ6c5wnxEZ9qDi5bMKmpjoTGeoixvEu15Zetr3MO00jnzMx4B/BR4i7cGps8yH9MQmie0OlT/a56JJwtX5sLYA4P40gptaCjY1pQDnPL0+dtW1sOhYwq/7WXtpUA5vJm8NeWvs+V7Z1+KSv9V3ZWqmB9DfA2SuDog/YMegmGgSyKZ20eolqGrHTWa6eOIuVdkUz2NjVRPjlOKvwhTwv0/ZaJIA+T9Ku3NmygC+hWpFptf1Z4R1S23zmrT+nbPxruW0vVQ3KK7es=CHE"