apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nginx
  namespace: {{ .Release.Namespace | quote }}
spec:
  template:
    type: Opaque
    metadata: 
  encryptedData:
    foo : "AgArg+xGgb8gkLC9wE032QBLqzd/dV25IA2UKg3aIHwB/QDRothD7WnXtEJ1/AwPStL1PJPtccAtl44Pz1L/cPEKaigdz7pJebJcJpJAQtwF5Q35vqNzeDEm6JHRvgqo2Rq7MxnWoCSAA+QEwWI2caxoF8WHgWUnPPVl17CgccPOS47qDokMNk9REk8ywjo4Q13LlOmOmqiHWzVYWS2hk76n1IG4Yuaj2UaKbGuBhgabAFePmoOn2wXl4aHK+cnGX/0GUhvmxH34V6ku0hj9sLgmcOyHu9dr7H4ViyLDfDKKdPH9411o7ViLqI99vc21stLxTQg9IzKqYcxJvk20r7hmUrXH7Hhud+keUjF6Crm24wMrevuMC16R7dRnsrT625RT/2AiNlWEgzMlMiycouyV/71rUCo24EL15B8fVtjVmo9HzUEOC+Sv9oFt8Kgrz4xHyjbUwZdD+tLbfQ+Sz7IzcZKMDAnVuadwen91vOLN2XdpsGBX+jaDXaQHODLULB37CyBp+7h4zJdAyTAyp9OgBZjJE3Ha86Vt3rrRiPq2bz0yisp9PyHb0ynXT0ndnoqMneHeb70CT36iSChlmUmLfzrLYFRCeQS02CGjabmgpvRbFLNf6YCb3Iz4ZFp22Y8HH3788BIefevKyOXs4JV8+G6vw01onc5W95Mz4mrKr1kR8I7AL1LIFy1qiPcJcuLZ9XY="