apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nginx
  namespace: {{ .Release.Namespace | quote }}
spec:
  template:
    type: Opaque
    metadata:      
  encryptedData:
    foo : "AgBcZoNthk90Dss57zWVJTLFGII/neUEpK1slLu2Rax1+9RBYw025Jl1mspnppZgjHeZgC4XNZOVFlquMXhBV+Jb5Nil1AZH6okyPeFXdARhI2r97lTbeocrRFGvNgt4wckhR2jI+FQ9LNzEfzdEJqmC1coLOtyuUsGBXnj01TvsRD5uttuvUc6yCHM+fwG5ERP4z58gTpMCXhn5kPdnQnrgjNCbmP2svR0svHo2jNRgqnzq11ZHFkW7w2GE5VuH3xIc68yZltVMvqil5gjW7+GorHyU6ct6myYvBQr6CKvZTA84voZPOQwQDKGOrPe234rGbUNhuOA/vAg6WDYwJjZJNJ2DvGdxznWxVdURJW47Zap3HWTJhCkPhXqrVDQehinAsDIDLZLp2vtOWbIPJ4BVlBhEGs/gqTBh/brZKbYfo/D2acVnQ72al3gkTfxmJ9XeRgiOrfUjq/5W3EISJRFUJ04zum5OMDs7eculMBDX3NyamxSGf2pze+NXUGlkgrObCJ07i/i7R/9f+414+BzsQ6vvS0txH8ApqPPnx705agBZ+7K0woWb/lhWtT8TNnq5wjjod6DmV5dNcTxhk+rKcs5ZcEoUQzR74hyPmV6we1TUoo5rGxmaPKPnVpHAeN/oCZ9iyQNuVo2rQTi+EgPxZJfjcMTR+zblxw8vhiQC1+3TRAb6UEp5Z6FQuzbvCN9w2QY="