apiVersion: v1
kind: Secret
metadata:
  name: nginx
type: Opaque
data:
  - foo : "AgCsEElh+dZFGKPEsELdtAUpFSfUDshp0Uk/sVdlMB4XCpqpeJToGPFXj/x4qzT5086WI7u1HYgq+gaGuCqoNIok5u12IoRPgVbsMjztfLZLzlvqr+XW2Bj+JKa7zrzoJsuqejQFYZ3CwrLgIoa1Au3A2rMXWiXeezFEkaHkCHe0PXZ4kvf1ApANUrqEYILTlAva1mLYf0k2QFcqPVaJf9Szn2upbq62+lP9vl5fVY/BJ3XlIMhQC/kz1nhzgbBhWq+aB7lC05INHH/9PjVrUwpL6Y8VrfLOnIk5qK4rezjopFZjrDDzdSqVTRrmsxJ6rJjYeu6bUY1b2SyUPUCTONzpc8lzZFc7DTrdi0zWlkLDO3+niWS4gVrcVBdU8ipPxYiYklcmM3MZzG7k1mK7PRbS7DPPgYH2WcsCmsS50JfJEKXSCA1mhaJnzfxtLV3dOpFn4OxG5AePpsCzckF7109Ap2SEnvuMjl5w6z1LNcADt5CWHjw22JJ4/sBHFe9GKsI4dqPHSMvFSkip3czVMAMa3cLPa6JwhjFFgT9JI9BY6xEoIvWmwAKKQFV6vKd916nKH8azzzx+DBL1KF6szz4U1Si/eF7kwlSrU7TvAz+06Fb9pV61U7535vH8+OW8AWiIxNTyQZIiYPttfeHnS5YExvKfeuPBjYOtMdpJF7kXRQ5ZVUG1SR+EztRCi426CTaKdFM=CHE"