apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    path: systemplugin/sealed-secrets
    repoURL: 'git@github.com:yx135790/Argocd-repository-leo.git'
    targetRevision: main
    helm:
      releaseName: sealed-secrets
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:    
    - CreateNamespace=true 