apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poc-app
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd/argocd-apps/poc-app
    repoURL: 'git@github.com:yx135790/Argocd-repository-leo.git'
    targetRevision: HEAD
  project: poc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
