apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-dr
  namespace: argocd
spec:
  project: default
  source:
    path: nginx/DR/
    repoURL: 'git@github.com:yx135790/Argocd-repository-leo.git'
    targetRevision: main
    helm:
      releaseName: nginx-dr
      valueFiles:
      - ../nginx-global.yaml
      - values-dr.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: web-dr
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:    
    - CreateNamespace=true 