apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-dev
  namespace: argocd
spec:
  project: default
  source:
    path: DEV/nginx/
    repoURL: 'git@github.com:yx135790/Argocd-repository-leo.git'
    targetRevision: main
    helm:
      releaseName: nginx-dev
      valueFiles:
      - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: web
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:    
    - CreateNamespace=true 