apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  source:
    path: nginx/ingress-nginx/
    repoURL: 'git@github.com:yx135790/Argocd-repository-leo.git'
    targetRevision: main
    helm:
      releaseName: ingress-nginx
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: web